#!/bin/sh
if [ ! -f /etc/inited ]; then
count=0
while :
do
	httping -c 1 www.baidu.com 1>/dev/null 2>&1
	if [ "$?" == "0" ]; then
opkg update
if [ -f /etc/config/jia ]; then
  opkg upgrade php7 php7-fpm php7-mod-dom php7-mod-fileinfo php7-mod-filter php7-mod-iconv php7-mod-json php7-mod-zip
  sed -i 's/service_start $PROG -y/service_start $PROG -R -y/g' /etc/init.d/php7-fpm
  sed -i "s/user =.*/user = root/g" /etc/php7-fpm.d/www.conf
  service php7-fpm restart
  opkg update
fi
	for ipk in $(cat /etc/installed-opkg); do
			opkg upgrade --force-depends $ipk
	done
	touch /etc/inited
	break
	fi
	sleep 5
	count=$((count+1))
	if [ $count -gt 60 ]; then
		break
	fi
done
rm -Rf /lib/upgrade/keep.d/php7*

sed -i 's/service_start $PROG -y/service_start $PROG -R -y/g' /etc/init.d/php7-fpm
sed -i "s/user =.*/user = root/g" /etc/php7-fpm.d/www.conf

find /www -type f -exec chmod 644 {} \;
find /www -type d -exec chmod 755 {} \;
chmod +x /usr/share/aria2/*.sh

ln -sf /usr/bin/python3 /usr/bin/python
ln -sf /usr/lib/netdata/conf.d /etc/netdata/conf.d
ln /usr/lib/netdata/conf.d/charts.d.conf /etc/netdata/charts.d.conf
ln /usr/lib/netdata/conf.d/python.d.conf /etc/netdata/python.d.conf
ln -f /etc/netdata/charts.d.conf /usr/lib/netdata/conf.d/charts.d.conf
ln -f /etc/netdata/python.d.conf /usr/lib/netdata/conf.d/python.d.conf

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/ksmbd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

if [ ! -f /etc/config/placeholder ]; then
  uci set mwan3.wan.enabled='0'
  uci commit mwan3
  
  uci del dockerman.local.daemon_ea
  uci commit dockerman
  
  uci -q set aria2.main.split="128"
  uci -q set aria2.main.min_split_size="100K"
  uci -q set aria2.main.max_connection_per_server="128"
  uci -q add_list aria2.main.extra_settings="dht-file-path=/usr/share/aria2/dht.dat"
  uci commit aria2
fi

rm -Rf /tmp
fi
