#!/bin/sh

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/snapshots\(.*luci\)/releases\/19.07-SNAPSHOT\1/g' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/customfeeds.conf
sed -i '$a src/gz openwrt_custom https://openwrt.supes.top:888/opkg' /etc/opkg/customfeeds.conf
sed -i 's/downloads.openwrt.org/mirrors.cloud.tencent.com\/openwrt/g' /etc/opkg/distfeeds.conf
sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i "s/127.0.0.1:5335/127.0.0.1:5555/g" /etc/AdGuardHome.yaml

rm -rf /tmp/luci-*

uci set smartdns.@smartdns[0].ipv6_server='0'
uci commit smartdns

[ $(uci get dhcp.@dnsmasq[0].filter_aaaa 2>/dev/null) ] || {
  uci set dhcp.@dnsmasq[0].filter_aaaa='1'
  uci commit dhcp
}
  
if [ ! -f /etc/config/placeholder ]; then
  uci set luci.main.lang=zh_cn
  uci set luci.main.mediaurlbase=/luci-static/argon
  uci commit luci

  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="10.0.0.1"
  uci set network.wan.proto=pppoe
  uci commit network
  
  uci set firewall.@defaults[0].fullcone='1'
  uci commit firewall
  
  uci set flowoffload.@flow[0].bbr='1'
  uci commit flowoffload
  
  uci set shadowsocksr.@global[0].pdnsd_enable='0'
  uci del shadowsocksr.@global[0].tunnel_forward
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.1.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='208.67.222.222'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.4.4'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='9.9.9.9'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='218.102.23.228'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='210.0.255.250'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='168.95.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.175.82.46'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='77.88.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='101.101.101.101'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='203.198.7.66'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.56.128.30'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='149.112.112.112'
  uci commit shadowsocksr
fi

if [ -f /etc/config/jia ]; then
  sed -i '/=\/tmp\/dnsmasq.ssr/d' /etc/init.d/shadowsocksr
  sed -i 's/service_start $PROG/service_start $PROG -R/g' /etc/init.d/php7-fpm
  sed -i "s/user =.*/user = root/g" /etc/php7-fpm.d/www.conf
fi

if [ ! -f /usr/bin/ssr-server ]; then
  sed -i '/server-config/d' /usr/lib/lua/luci/controller/shadowsocksr.lua
fi

cp -R /www/cgi-bin/* /www/
find /www -type f -exec chmod 644 {} \;
find /www -type d -exec chmod 755 {} \;
chmod +x /www/luci

sed -i "s/git-.*-\(.*\)/git-\1/g" /usr/lib/lua/luci/version.lua

count=0
while :
do
	httping -c 1 www.baidu.com 1>/dev/null 2>&1
	if [ "$?" == "0" ]; then
opkg update
if [ -f /etc/config/jia ]; then
  opkg upgrade php7 php7-fpm php7-mod-dom php7-mod-fileinfo php7-mod-filter php7-mod-iconv php7-mod-json php7-mod-zip
  sed -i 's/service_start $PROG -y/service_start $PROG -R -y/g' /etc/init.d/php7-fpm
  sed -i "s/user =.*/user = root/g" /etc/php7-fpm.d/www.conf
  /etc/init.d/php7-fpm restart
  [ "`pgrep php-fpm`" ] || {
	/etc/init.d/php7-fpm restart
	}
  opkg update
fi
cp -r /etc/config /etc/config.bak
	for ipk in $(cat /etc/installed-opkg); do
			opkg upgrade --force-depends $ipk
	done
rsync -av /etc/config.bak/* /etc/config --exclude='ucitrack'  --exclude='dhcp'  --exclude='firewall'  --exclude='network'  --exclude='system'
rm -Rf /etc/config.bak
	  [ "`pgrep unblockmusic`" ] || {
	/etc/init.d/unblockmusic restart
	}
	break
	fi
	sleep 5
	count=$((count+1))
	if [ $count -gt 60 ]; then
		break
	fi
done

touch /etc/config/placeholder

exit 0
