#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/http/https/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-*

if [ ! -f /etc/config/placeholder ]; then
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="10.0.0.1"
  uci set network.lan.ifname="eth1"
  uci set network.wan.ifname="eth0"
  uci set network.wan.proto=pppoe
  uci commit network
  
  uci set shadowsocksr.@global[0].pdnsd_enable='0'
  uci del shadowsocksr.@global[0].tunnel_forward
  
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.1.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='208.67.222.222'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.4.4'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='9.9.9.9'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='218.102.23.228'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='210.0.255.250'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='168.95.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.86.191.50'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='77.88.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='101.101.101.101'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='203.198.7.66'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.56.128.30'
  uci commit shadowsocksr
  
  uci set AdGuardHome.AdGuardHome.redirect='dnsmasq-upstream'
  uci set AdGuardHome.AdGuardHome.enabled='1'
  uci commit AdGuardHome
  
  uci del dhcp.@dnsmasq[0].resolvfile
  uci set dhcp.@dnsmasq[0].noresolv='1'
  uci commit dhcp
  
  uci -q set aria2.main.split="128"
  uci -q set aria2.main.min_split_size="100K"
  uci -q set aria2.main.max_connection_per_server="128"
  uci -q add_list aria2.main.extra_settings="dht-file-path=/usr/share/aria2/dht.dat"
  uci commit aria2
fi

if [ -f /etc/config/jia ]; then
  sed -i '/=\/tmp\/dnsmasq.ssr/d' /etc/init.d/shadowsocksr
fi

/etc/init.d/amule disable
find /www -type f -exec chmod 644 {} \;
find /www -type d -exec chmod 755 {} \;
cp -R /www/cgi-bin/* /www/
chmod +x /www/luci
chmod +x /usr/share/aria2/*.sh


ln -sf /usr/bin/python3 /usr/bin/python
ln -sf /usr/bin/python /usr/bin/py
ln -sf /usr/lib/netdata/conf.d /etc/netdata/conf.d
ln /usr/lib/netdata/conf.d/charts.d.conf /etc/netdata/charts.d.conf
ln /usr/lib/netdata/conf.d/python.d.conf /etc/netdata/python.d.conf
ln -f /etc/netdata/charts.d.conf /usr/lib/netdata/conf.d/charts.d.conf
ln -f /etc/netdata/python.d.conf /usr/lib/netdata/conf.d/python.d.conf

sed -i '/ipv6.conf/d' /etc/sysctl.conf
echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
echo net.ipv6.conf.lo.disable_ipv6 = 1 >> /etc/sysctl.conf

date=`date +%m.%d.%Y`
sed -i "s/DISTRIB_REVISION.*/DISTRIB_REVISION=\"Compiled by GaryPnag  $date\"/g" /etc/openwrt_release

touch /etc/config/placeholder

exit 0
