#!/bin/sh

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/snapshots\(.*luci\)/releases\/19.07-SNAPSHOT\1/g' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/customfeeds.conf
sed -i 's/downloads.openwrt.org/mirrors.cloud.tencent.com\/openwrt/g' /etc/opkg/distfeeds.conf
sed -i 's/http:/https:/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i '/profile.d/d' /lib/upgrade/keep.d/base-files
sed -i 's/\[ -e "$FILE" \] && . "$FILE"/[ -e "$FILE" ] \&\& env -i bash "$FILE"/g' /etc/profile

rm -rf /tmp/luci-*

[ -f /etc/init.d/https-dns-proxy ] && /etc/init.d/https-dns-proxy disable

sed -i '/S99opkg/d' /etc/crontabs/root
echo "0 0 */3 * * sh /etc/rc.d/S99opkg >/dev/null 2>&1" >> /etc/crontabs/root

if [ ! -f /etc/config/placeholder ]; then

	if [ $(uci get network.wan.ipv6) == 0 ]; then
		uci set smartdns.@smartdns[0].ipv6_server='0'
		uci commit smartdns

			uci set dhcp.@dnsmasq[0].filter_aaaa='1'
			uci commit dhcp
	else
		uci set smartdns.@smartdns[0].ipv6_server='1'
		uci commit smartdns

		uci set dhcp.@dnsmasq[0].filter_aaaa='0'
		uci commit dhcp
	fi

  uci set luci.main.lang=auto
  uci set luci.main.mediaurlbase=/luci-static/edge
  uci commit luci
  
  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="10.0.0.1"
  uci set network.wan.proto=pppoe
  uci commit network

  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.1.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.0.0.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.4.4'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='9.9.9.9'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='146.112.41.2'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='104.16.248.249'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='104.16.249.249'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='149.112.112.112'
  uci add_list shadowsocksr.@access_control[0].wan_bp_ips='210.0.255.250'
  uci add_list shadowsocksr.@access_control[0].wan_bp_ips='168.95.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_bp_ips='101.101.101.101'
  uci add_list shadowsocksr.@access_control[0].wan_bp_ips='210.17.9.228'
  uci add_list shadowsocksr.@access_control[0].wan_bp_ips='203.198.7.66'
  uci commit shadowsocksr

fi

if [ -f /etc/config/jia ]; then
  sed -i '/=\/tmp\/dnsmasq.ssr/d' /etc/init.d/shadowsocksr
fi
if [ ! -f /usr/bin/ssr-server ]; then
  sed -i '/server-config/d' /usr/lib/lua/luci/controller/shadowsocksr.lua
fi

cp -R /www/cgi-bin/* /www/
find /www -type d -exec chmod 755 {} \;
chmod +x /www/luci

sed -i "s/git-.*-\(.*\)/git-\1/g" /usr/lib/lua/luci/version.lua

