#!/bin/sh

ln -sf /sbin/ip /usr/bin/ip

sed -i 's/snapshots\(.*luci\)/releases\/19.07-SNAPSHOT\1/g' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/customfeeds.conf
sed -i '$a src/gz openwrt_custom_luci https://op.supes.top:88/ramips/luci' /etc/opkg/customfeeds.conf
# sed -i '$a src/gz openwrt_custom_core https://op.supes.top:88/ramips/kmod' /etc/opkg/distfeeds.conf
sed -i 's/downloads.openwrt.org/mirrors.cloud.tencent.com\/openwrt/g' /etc/opkg/distfeeds.conf
sed -i 's/http:/https:/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i '/profile.d/d' /lib/upgrade/keep.d/base-files
sed -i 's/\[ -e "$FILE" \] && . "$FILE"/[ -e "$FILE" ] \&\& env -i bash "$FILE"/g' /etc/profile

rm -rf /tmp/luci-*

uci set smartdns.@smartdns[0].ipv6_server='0'
uci commit smartdns

[ $(uci get dhcp.@dnsmasq[0].filter_aaaa 2>/dev/null) ] || {
  uci set dhcp.@dnsmasq[0].filter_aaaa='1'
  uci commit dhcp
}
 
if [ ! -f /etc/config/placeholder ]; then

  uci set luci.main.lang=zh_cn
  uci set luci.main.mediaurlbase=/luci-static/edge
  uci commit luci
  
  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  sed -i 's/root:.*/root:$1$tTPCBw1t$ldzfp37h5lSpO9VXk4uUE\/:18336:0:99999:7:::/g' /etc/shadow
  uci set network.lan.ipaddr="10.0.0.1"
  uci set network.wan.proto=pppoe
  uci commit network
  
  uci set firewall.@defaults[0].fullcone='1'
  uci set firewall.@defaults[0].flow_offloading_hw='1'
  uci commit firewall
  
  uci set flowoffload.@flow[0].bbr='1'
  uci commit flowoffload
  
fi

cp -R /www/cgi-bin/* /www/
find /www -type d -exec chmod 755 {} \;
chmod +x /www/luci

sed -i "s/git-.*-\(.*\)/git-\1/g" /usr/lib/lua/luci/version.lua

touch /etc/config/placeholder

exit 0
