#!/bin/sh

exec >/var/persist-packages.log 2>&1

count=0
while :; do
	httping -c 1 www.baidu.com >/dev/null 2>&1
	if [ "$?" == "0" ]; then
		opkg update
		if [ ! -f /etc/inited ]; then
			[ uci get dhcp.@dnsmasq[0].noresolv ] && {
				uci del dhcp.@dnsmasq[0].noresolv
				uci commit dhcp
				service dnsmasq reload
			}

			cp -r /etc/config /etc/confbak
			for ipk in $(cat /etc/backup/installed_packages.txt | grep -oE '.*overlay' | awk '{print $1}'); do
				opkg upgrade --force-depends --force-checksum $ipk
			done

			[ -f "/etc/installed-opkg" ] && {
				for ipk in $(cat /etc/installed-opkg); do
					opkg upgrade --force-depends --force-checksum $ipk
				done
			}

			find /etc/confbak -type f ! -path '*/ucitrack' ! -path '*/dhcp' ! -path '*/firewall' ! -path '*/network' ! -path '*/system' -exec cp '{}' '/etc/config/{}' \;
			rm /etc/config/.*-opkg
			source /etc/profile.d/opkginstall.sh
			opkg install >/dev/null 2>&1
			httping -c 1 https://openwrt.supes.top:888 >/dev/null 2>&1
			if [ "$?" == "0" ]; then
				touch /etc/inited
			fi

		fi
		rm -f /var/lock/opkg.lock
		break
	fi
	sleep 5
	count=$((count + 1))
	if [ $count -gt 120 ]; then
		break
	fi
done

if [ `uci get network.wan.ipv6` == 0 ]; then
	sysctl -w net.ipv6.conf.all.disable_ipv6=1
	sysctl -w net.ipv6.conf.lo.disable_ipv6=1
	sysctl -w net.ipv6.conf.default.disable_ipv6=1
	echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
else
	sysctl -w net.ipv6.conf.all.disable_ipv6=0
	sysctl -w net.ipv6.conf.lo.disable_ipv6=0
	sysctl -w net.ipv6.conf.default.disable_ipv6=0
	echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
fi
